# Omakase Ruby styling for Rails
inherit_gem: { rubocop-shopify: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Rails/Exit:
  Exclude:
    - spec/rails_helper.rb

Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
