services:
  web:
    build: .
    image: rails_sandbox:7.2.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_rails7.2.0:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: postgres:16.3-alpine3.20
    volumes:
      - pgsqldb16.3:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  # mysql:
  #   image: mysql:8.4.0
  #   volumes:
  #     - mysqldb8.4:/var/lib/mysql
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgsqldb16.3:
    driver: local
  bundle_rails7.2.0:
    driver: local
  # mysqldb8.4:
  #   driver: local
