services:
  web:
    build: .
    image: rails_sandbox:8.0.0rc1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_rails8.0.0rc1:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: postgres:16.4-alpine3.20
    volumes:
      - pgsqldb16.4:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  # mysql:
  #   image: mysql:8.4.0
  #   volumes:
  #     - mysqldb8.4:/var/lib/mysql
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgsqldb16.4:
    driver: local
  bundle_rails8.0.0rc1:
    driver: local
  # mysqldb8.4:
  #   driver: local
