services:
  web:
    image: rails_sandbox:8.1.1
    build: .
    ports:
      - "${RAILS_PORT:-3000}:3000"
    volumes:
      - ./sandbox:/app
      - rails8.1.1:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - OIDC__ISSUER=${OIDC__ISSUER}
      - OIDC__REDIRECT_URI=${OIDC__REDIRECT_URI}
      - OIDC__SIGNING_KEY=${OIDC__SIGNING_KEY}
      - OIDC__CLIENT_ID=${OIDC__CLIENT_ID}
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    volumes:
      - keycloak:/opt/keycloak/data
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_USER:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-admin}
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    command: start-dev
  postgres:
    image: postgres:18.0-alpine
    volumes:
      - pgsqldb18.0:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  # db:
  #   image: mysql:8.0.33
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - mysqldb8.0:/var/lib/mysql
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgsqldb18.0:
    driver: local
  # mysqldb8.0:
  #   driver: local
  rails8.1.1:
    driver: local
  keycloak:
    driver: local
