# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c16b852e95807fdead6b5233ffea92dd2da15d9abd9341859732e04ff472e0fb98b9f9bbf43f3fe23409fb5d101b7e407e49c9081a070ba455442577c02d2d0

test:
  secret_key_base: 6bd53c72c9d894f44d545e2e6e50472eaa149381617ba1811441ba03cae298da36709fff857f1c08b9adcabc31fae3adca6cf48dcc16ee4012b3a363650f69e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
